#ifndef RENDERPROVIDER_H__
#define RENDERPROVIDER_H__

#define ETCS_DLL_EXPORTS
#include "../../core_defs.h"
#include "../../ontology.h"
#include "Contract_RenderProvider.h"

#include <string>

// RenderProvider -- Vulkan, two tags:
//
//   Instance -- the VkInstance/device/queue/command pool. Flat (no
//               ontology supertype but Deletable): there is one Vulkan
//               backend, and nothing addresses "an instance" generically.
//   Target   -- a 2D render target (Target_ + Resizable_, see
//               ontology/TargetBase.h). Spawned as a CHILD of a
//               WindowProvider::Window; reaches its parent through the
//               generic interface-pointer surface, never through a
//               compile-time dependency on WindowProvider.
//
// Deliberately absent in V1, all flagged rather than forgotten:
//   - validation layers (VulkanInstance::Create's own comment)
//   - textures/image blit (the primitive PintaProvider will actually need
//     for a canvas -- next milestone, once this one presents pixels)
//   - a script-driven frame loop: .etcs has no loop construct today, so
//     Target.RunDemo drives frames internally the way Window.Run already
//     does. That is a stopgap for manual verification, not the shape the
//     eventual editor should use.

// ── Instance ─────────────────────────────────────────────────────────────

DEFINE_WORK_FUNC(Instance, Create)
{
    (void)ctx; (void)data;
    if (!self.Create())
        ETCS_LOG("Instance::Create", "Vulkan instance bring-up failed.");
}

DEFINE_WORK_FUNC(Instance, Delete)
{
    (void)ctx; (void)data;
    self.DeleteConcrete();
}

// ── Target ───────────────────────────────────────────────────────────────

// Create <instance_rid> [<shader_dir>] -- the RID is parsed off the raw
// buffer rather than declared as a typed field, matching HttpServer's own
// AddHandler/AddRoute convention (NetworkProvider.h) for taking a
// script-supplied @name. shader_dir defaults to "shaders/", resolved
// relative to the process cwd exactly like FileHtmlPage::LoadFromDisk's
// path -- nothing in this codebase locates a module's own install
// directory yet, and inventing that mechanism here would be a bigger
// change than this milestone warrants.
DEFINE_WORK_FUNC(Target, Create)
{
    (void)ctx;
    ETCS::RID   instance_rid = 0;
    std::string shader_dir;
    data >> instance_rid;
    data >> shader_dir;

    if (instance_rid == 0)
    {
        ETCS_LOG("Target::Create", "no Instance RID given -- spawn a RenderProvider::Instance, "
                                    "call Create on it, and pass it here.");
        return;
    }

    // Via this module's own EventNode ridMap rather than _ridlist_Instance()
    // directly: that function is generated by ETCS_TAG_DECLARE, which runs
    // in RenderProvider.cc AFTER this header is included, so it isn't in
    // scope here. The map row is registered by the same macro at static
    // init (EventNode::RegisterRIDRegistry), which is reachable generically.
    auto& ridMap = ETCS::EventNode::getInstance().ridMap;
    auto it = ridMap.find(ETCS::Buffer("Instance"));
    if (it == ridMap.end())
    {
        ETCS_LOG("Target::Create", "no Instance ridlist registered in this module.");
        return;
    }
    ETCS::Entity* raw = it->second.invoke_get(instance_rid);
    if (!raw)
    {
        ETCS_LOG("Target::Create", "RID:" << instance_rid << " is not a RenderProvider::Instance.");
        return;
    }
    // getTrueType(), not a static_cast off Entity*: Entity is a VIRTUAL
    // base here, so a direct downcast from it is ill-formed -- this is the
    // same recovery route the work-func trampolines themselves use.
    Instance* instance = static_cast<Instance*>(raw->getTrueType());

    if (!self.Create(instance, shader_dir))
        ETCS_LOG("Target::Create", "target bring-up failed.");
}

DEFINE_WORK_FUNC_TYPED(Target, Clear, (float, r), (float, g), (float, b), (float, a))
{
    (void)ctx;
    self.Clear(r, g, b, a);
}

DEFINE_WORK_FUNC_TYPED(Target, DrawRect, (int32_t, x), (int32_t, y), (uint32_t, w), (uint32_t, h),
                                          (float, r), (float, g), (float, b), (float, a))
{
    (void)ctx;
    self.DrawRect(x, y, w, h, r, g, b, a);
}

DEFINE_WORK_FUNC(Target, Present)
{
    (void)ctx; (void)data;
    self.Present();
}

DEFINE_WORK_FUNC(Target, Delete)
{
    (void)ctx; (void)data;
    self.DeleteConcrete();
}

// Manual-verification convenience -- see this file's own header comment.
DEFINE_WORK_FUNC_TYPED(Target, RunDemo, (uint32_t, frames))
{
    (void)ctx;
    ETCS::Entity* parent = self.getParent();
    if (!parent)
    {
        ETCS_LOG("Target::RunDemo", "no parent window to poll.");
        return;
    }
    self.RunDemo(parent, frames);
}

#endif
